### ISSUE TITLE
Periodic hash-mismatch errors

### ISSUE THREAD

**Issue by mikepurvis** [nix-community/harmonia#113] opened 2023-07-12 04:42 UTC
My production deployment of Harmonia is periodically hitting this:

```
$ nix build /nix/store/sj3bn7358h7yv0ay4lnlx239pdjggcl2-thingy
error: hash mismatch importing path '/nix/store/sj3bn7358h7yv0ay4lnlx239pdjggcl2-thingy';
         specified: sha256:0qkdh21a1s90y7x0d1dzcs6bf2ixrbdmmqkggbx0y5hvigqd2xwr
         got:       sha256:0y9ckb5pfdsfagcllk4mcnzi78m4pph882dissgbzp7zgzycrwr8
```

When I compute the store path narhash with `nix hash` from onboard the Harmonia host, I get the "got" value, and furthermore, restarting Harmonia appears to correct it— so it definitely seems to be a problem that is originating from _inside_ Harmonia.

There was some speculation that Harmonia's leveraging of the Nix store API was a possible cause for this:

https://github.com/NixOS/nix/blob/27f82ef4a8fc589738ef06040dad5c0e214f97aa/src/libstore/store-api.cc#L658-L664

**Comment by mikepurvis** [comment] 2023-08-03 20:14
I'd love to be able to make progress on this, but I will need some additional guidance from maintainers on where to begin with fixing it.

**Comment by Mic92** [comment] 2023-08-07 07:49
I think the problem is internal caching when querying from the sqlite within nix so that hash changes are not observed.
1. We would either read from the database with rust directly instead of libstore from nix
2. Convince nix upstream to allow disabling the cache
3. Restart harmonia every once in a while to disable the cache.

**Comment by Mic92** [comment] 2023-08-07 07:56
Ah there might be a setting that allows to disable the in-memory cache:

https://github.com/NixOS/nix/blob/9113b4252b5cebebb929915dd0f3e230238be1ab/src/libstore/store-api.hh#L143

**Comment by Mic92** [comment] 2023-08-07 08:06
Should be resolved in https://github.com/nix-community/harmonia/pull/129

**Closed** 2023-08-07 08:43 UTC
